spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true      # H2 콘솔 사용 여부
      path: /h2-console  # 콘솔 접속 경로 (http://localhost:8080/h2-console)

  jpa:
    hibernate:
      ddl-auto: create   # 애플리케이션 실행 시 테이블 생성
    show-sql: true       # 실행되는 SQL 로그 출력

server:
  error:
    whitelabel:
      enabled: true   # Whitelabel 페이지 활성화